### ISSUE TITLE
Going from development to distribution

### ISSUE THREAD

**Issue by markusthegeek** [nanonation/floatsign#1]
Hi John,

I really like your version of this script and am interested in using it once we have switched all of our build servers over to Xcode 6 (code signing without the --resource-rules option).

Here is some code I added on my side in between the replacement of the app ID and team ID and the plutil line. This ensures that entitlements are set correctly when you build with development profile and then resign with distribution and vice versa. Maybe useful for you as well?

gruss,
Markus

---

``` bash
if [[ "$CERTIFICATE" == *Distribution* ]]; then
    # new beta key is only used for Distribution; might not exist yet, if we were building Development
      `PlistBuddy -c "Add :beta-reports-active bool true" temp/newEntitlements`
      if [ $? -ne 0 ]; then
      `PlistBuddy -c "Set :beta-reports-active YES" temp/newEntitlements`
    fi
    checkStatus
      echo "Assuming Distribution Identity. Setting get-task-allow=NO"
    `PlistBuddy -c "Set :get-task-allow FALSE" temp/newEntitlements`
  else
    # if we were building with Distribution profile, we have to delete the beta key
    `PlistBuddy -c "Delete :beta-reports-active" temp/newEntitlements`
    # do not check status here, just let it fail if entry does not exist
      echo "Assuming Development Identity. Setting get-task-allow=YES"
    `PlistBuddy -c "Set :get-task-allow YES" temp/newEntitlements`
  fi
  checkStatus
```

**Comment by GoannaGuy** [comment]
Markus,

I'm testing your changes, my only concern is if setting the 'beta-reports-active' flag to true should be a command line option.

FYI, I just pushed an updated version of the script that fixes some bugs with the original file. Previously the script assumed that your were running it in the same directory as the IPA or App, now it can handle full or relative paths. It also failed on file names that had more than one period in the name.

The script also now allows you to specify a new version number (-n 1.2.3) to use for the CFBundleVersion and CFBundleShortVersionString (if present) in the app's Info.plist.

-=- John

On Nov 19, 2014, at 7:25:40 PM, markusthegeek <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi John,

I really like your version of this script and am interested in using it once we have switched all of our build servers over to Xcode 6 (code signing without the --resource-rules option).

Here is some code I added on my side in between the replacement of the app ID and team ID and the plutil line. This ensures that entitlements are set correctly when you build with development profile and then resign with distribution and vice versa. Maybe useful for you as well?

gruss,
Markus

---

if [[ "$CERTIFICATE" == _Distribution_ ]]; then
    # new beta key is only used for Distribution; might not exist yet, if we were building Development
      `PlistBuddy -c "Add :beta-reports-active bool true" temp/newEntitlements`
      if [ $? -ne 0 ]; then
      `PlistBuddy -c "Set :beta-reports-active bool true" temp/newEntitlements`
    fi
    checkStatus
      echo "Assuming Distribution Identity. Setting get-task-allow=NO"
    `PlistBuddy -c "Set :get-task-allow bool false" temp/newEntitlements`
  else
    # if we were building with Distribution profile, we have to delete the beta key
    `PlistBuddy -c "Delete :beta-reports-active" temp/newEntitlements`
    # do not check status here, just let it fail if entry does not exist
      echo "Assuming Development Identity. Setting get-task-allow=YES"
    `PlistBuddy -c "Set :get-task-allow bool true" temp/newEntitlements`
  fi
  checkStatus

**Comment by markusthegeek** [comment]
Hi John,

Thanks for looking into this. The beta flag is mandatory for all new distribution profiles going forward to work with the new Testflight beta option. Thus I guess it can always be added for dist but should never for dev profiles.

Your other changed sound great as well! Keep up the good work.

Eventually, I hope that all entitlements are only set in the profiles and no additions in Xcode. Then we could simplify the logic to just override the binary with the current profile and do away with all the special replacement rules. Guess we would just codesign without the entitlements option in that case or point to the embedded.profile?

Gruss,
Markus

**Comment by GoannaGuy** [comment]
Markus,

I was more thinking that the beta-reports may not be necessary, or worse cause conflicts, with Enterprise distribution resigning when not using TestFlight, or recently generated profiles. I've had quite a few run-ins lately with entitlements in provisioning profiles not matching those in the app's entitlements file, so I'm a little gun-shy of adding/enforcing extra entitlements.

-=- John

**Comment by markusthegeek** [comment]
Hi John,

oops, I meant to leave a comment, maybe I did not save it correctly.

maybe in this case you original idea is better to introduce yet another argument to enable my logic above?

gruss,
Markus

**Comment by markusthegeek** [comment]
Hi John,

would the above proposal with an additional argument for my code block be an option for you?

gruss,
Markus

**Comment by GoannaGuy** [comment]
Markus,

The optional argument is the way to go.

I'll try to get it merged in later today.

-=- John

**Comment by markusthegeek** [comment]
Thanks, John,

Looking forward to testing this in the next couple of weeks while things are a little more quiet.

Gruss,
Markus

**Comment by GoannaGuy** [comment]
Markus,

Sorry for the delay. Please try the latest commit https://github.com/nanonation/floatsign/commit/467cdbf09bd8b1b4d523a381e5eec11099e11e98 with the new "-r adjustBetaReports" flag.

Thanks,

-=- John

**Comment by markusthegeek** [comment]
Hi John,

new option looks great, your script is working here for me!

two comments:
- I got an error with the setting of the keychain-access-groups because my app binary does not contain this setting; what I did is comment out the checkStatus call in line 360

https://github.com/nanonation/floatsign/blob/master/floatsign.sh#L360
- looks like -r needs an argument e.g. "-r yes"; do you want to make this clearer in the included comment line help?

gruss,
Markus

**Comment by GoannaGuy** [comment]
Markus,

I incorporated changes to address your comments in the latest commit https://github.com/nanonation/floatsign/commit/86e2b559e9b695b14bf8db69b742dd8ef8c60ed6

-=- John

**Comment by markusthegeek** [comment]
Hi John,

Thanks a lot for doing this! Looks great, will give this another try next week and then close my request!

Gruss,
Markus

**Comment by markusthegeek** [comment]
Hi John,

everything is working great now on my machine and the build server. thanks again for getting this in, I will keep syncing with your changes going forward!

gruss,
Markus
